### ISSUE TITLE
Background too wide

### ISSUE THREAD

**Issue by eerimoq** [ksemianov/WrappingHStack#4]
Hi!

First of all, I tried three different libraries similar to this on Github. This library is the best!

I'm not sure whether I'm missing something or if it is something that can/should be fixed in this library. When I use a SwiftUI `HStack` the background color is only as wide as its contents. With `WrappedHStack` the background color fills the whole parent view width.

With `HStack`:

![0D0F92B0-1C99-492C-8773-76B968AD72A6](https://github.com/ksemianov/WrappingHStack/assets/176810/b0682b28-2ef4-4acf-8a01-1ac96a7edd4b)

With `WrappedHStack`:

![F88C24B8-0C67-4EA8-9521-008FF7B083DF](https://github.com/ksemianov/WrappingHStack/assets/176810/6da5ebab-6a92-4ad4-b1d4-3f7085347e64)

Any tips on what I can do to get the `HStack` background color behavior with `WrappedHStack`?

The code with `HStack` can be found here: https://github.com/eerimoq/mobs/blob/71b0e1efda05967004aaf0ad1cdd616bc45c37ed/Mobs/View/Stream/Overlay/StreamOverlayChatView.swift#L42

**Comment by ksemianov** [comment]
@eerimoq, thanks for your positive feedback! I've prepared a [PR](https://github.com/ksemianov/WrappingHStack/pull/5) incorporating the feature you mentioned. Would you mind giving it a try? To test it, reference commit 4396e80f8ddc8d597806c48737b4927b334b58fa instead of a version number and include `fitContentWidth: true` in the `WrappingHStack` initializer. If everything checks out, I plan to release it as version `0.2.0`.

**Comment by eerimoq** [comment]
It works. Thank you very much for the new feature!

I tested without the new parameter as well, and it worked like before, just as expected.

**Comment by ksemianov** [comment]
Thank you for the confirmation. I‘ve released `0.2.0`.
